Update video instrumentation
1. Include ifstats RX_DROPS in PacketDiscardCount.
2. Remove redundant tests of netdev module in ethernet,
   moca, and wifi DMs.
3. Add new drop counters exported from mcastcapture.
4. Redo netdev.py using current infrastructure, use
   tr.types.ReadOnly where possible.
5. Make tr.types.Int types handle numbers >32 bits.
   Was getting this on MIPS:
   OverflowError: Python int too large to convert to C long
   Added unit test, though the problem does not manifest
   on x86_64 only on a 32 bit platform.
6. Generalize per-queue drop count handling, allow platform
   to pass in file pattern.
7. Export an integer count of high priority packets dropped,
   simpler to graph. Full list of all queues is also exported.
8. Implement automatic reset for StallAlarm as agreed with
   ACS team.
9. Fix SetParameterValues for vendor parameters like
   X_CATAWAMPUS-ORG_Foo, and add a unit test in
   acs_integration_test to make sure it works.
10. Fix pylint errors.

Change-Id: I96eb8fd0d5f1fbded44fe4d6f05c7e28c32f4b7d